"""initial schema

Revision ID: 6c7d8a89fe52
Revises: 
Create Date: 2026-07-15 23:55:58.941279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c7d8a89fe52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_policies_org_id'), 'payment_policies', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_oauth_token', sa.String(), nullable=True),
    sa.Column('oauth_scopes', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(), server_default='en', nullable=False),
    sa.Column('plan_tier', sa.String(), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_org_id'), 'vendors', ['org_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default='completed', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_user_id'), 'agent_logs', ['user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('file_path_or_url', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), server_default='Member', nullable=False),
    sa.Column('indexing_status', sa.String(), server_default='queued', nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_org_id'), 'knowledge_documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'knowledge_documents', ['user_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('policy_check_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_invoice_id'), 'payment_records', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_records_org_id'), 'payment_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('template_structure', sa.String(), nullable=False),
    sa.Column('tone_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_org_id'), 'playbooks', ['org_id'], unique=False)
    op.create_index(op.f('ix_playbooks_user_id'), 'playbooks', ['user_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_org_id'), 'purchase_orders', ['org_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_user_id'), 'purchase_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=False),
    sa.Column('thread_summary', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_thread_id', name='uq_user_gmail_thread')
    )
    op.create_index(op.f('ix_threads_gmail_thread_id'), 'threads', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('vip_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_email', name='uq_user_vip_contact_email')
    )
    op.create_index(op.f('ix_vip_contacts_contact_email'), 'vip_contacts', ['contact_email'], unique=False)
    op.create_index(op.f('ix_vip_contacts_user_id'), 'vip_contacts', ['user_id'], unique=False)
    op.create_table('email_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), server_default='Medium', nullable=False),
    sa.Column('category', sa.String(), server_default='General', nullable=False),
    sa.Column('urgency', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reply_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('suspicious_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_message_id', name='uq_user_gmail_message')
    )
    op.create_index(op.f('ix_email_metadata_gmail_message_id'), 'email_metadata', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_email_metadata_thread_id'), 'email_metadata', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_metadata_user_id'), 'email_metadata', ['user_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('current_body', sa.String(), nullable=False),
    sa.Column('version_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(), server_default='drafting', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_email_id'), 'drafts', ['email_id'], unique=False)
    op.create_index(op.f('ix_drafts_thread_id'), 'drafts', ['thread_id'], unique=False)
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_email_id', sa.Uuid(), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('proposed_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(), server_default='previewed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_email_id'], ['email_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_source_email_id'), 'meetings', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_table('conversation_context',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('active_email_id', sa.Uuid(), nullable=True),
    sa.Column('active_thread_id', sa.Uuid(), nullable=True),
    sa.Column('active_draft_id', sa.Uuid(), nullable=True),
    sa.Column('last_search_query', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['active_email_id'], ['email_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['active_thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_user_session_context')
    )
    op.create_index(op.f('ix_conversation_context_session_id'), 'conversation_context', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_context_user_id'), 'conversation_context', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_context_user_id'), table_name='conversation_context')
    op.drop_index(op.f('ix_conversation_context_session_id'), table_name='conversation_context')
    op.drop_table('conversation_context')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_source_email_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_thread_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_email_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_email_metadata_user_id'), table_name='email_metadata')
    op.drop_index(op.f('ix_email_metadata_thread_id'), table_name='email_metadata')
    op.drop_index(op.f('ix_email_metadata_gmail_message_id'), table_name='email_metadata')
    op.drop_table('email_metadata')
    op.drop_index(op.f('ix_vip_contacts_user_id'), table_name='vip_contacts')
    op.drop_index(op.f('ix_vip_contacts_contact_email'), table_name='vip_contacts')
    op.drop_table('vip_contacts')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_gmail_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_org_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_playbooks_user_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_org_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_payment_records_user_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_org_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_invoice_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_org_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_agent_logs_user_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_vendors_org_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_policies_org_id'), table_name='payment_policies')
    op.drop_table('payment_policies')
    # ### end Alembic commands ###
