"""add_user_voice_fields

Revision ID: abe89086009f
Revises: e6d5b77c128f
Create Date: 2026-07-17 22:14:08.234384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe89086009f'
down_revision: Union[str, Sequence[str], None] = 'e6d5b77c128f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('google_integrations_user_id_key'), 'google_integrations', type_='unique')
    op.add_column('users', sa.Column('voice_profile_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_history_opt_in', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voice_history_opt_in')
    op.drop_column('users', 'voice_profile_id')
    op.create_unique_constraint(op.f('google_integrations_user_id_key'), 'google_integrations', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
